@startuml
caption Схема навигации страниц
component [Главная страница] as mPage
component [Список студентов] as sLPage
component [Персональная страница \nстудента] as sPage
component [Список преподавателей] as tLPage
component [Персональная страница \nпреподавателя] as tPage
component [Список курсов] as crLPage
component [Страница курса] as crPage
component [Список групп] as gLPage
component [Страница группы] as gPage
component [Список компаний] as cmLPage
component [Страница компании] as cmPage
component [Генератор расписания] as sGPage
component [Страница с готовым \nрасписанием] as sRPage
component [Редактор расписания] as eSPage


mPage -d-> tLPage : Просмотр списка \nпреподавателей
mPage -d-> sLPage : Просмотр списка \nстудентов
mPage -d-> crLPage : Просмотр списка \nкурсов
mPage -d-> cmLPage : Просмотр списка \nкомпаний
mPage -d-> gLPage : Просмотр списка \nгрупп студентов
mPage -d-> sGPage : Создать картинку \nс расписанием
mPage -d-> eSPage : Редактировать расписание

tLPage -d-> tPage : Просмотр/изменение \nпреподавателя
sLPage -d-> sPage : Просмотр/изменение \nстудента
crLPage -d-> crPage : Просмотр/изменение \nкурса
cmLPage -d-> cmPage : Просмотр/изменение \nкомпании
gLPage -d-> gPage : Просмотр/изменение \nгруппы

sGPage -d-> sRPage : Просмотр готового \nрасписания

tPage -d-> crPage : Проводимые курсы
tPage -d-> cmPage : Компания
crPage -d-> tPage : Преподаватель курса
cmPage -d-> crPage : Проводимые курсы
sPage -d-> crPage : Прослушанные курсы

gPage -d-> sPage : Студенты группы
gPage -d-> crPage : Группа курса

@enduml